### ISSUE TITLE
Swap out logo

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/template#1]
The logo should probably replaced to be consistent with current brand guidelines.  I've done a version that uses the new circular logo at https://github.com/caltechlibrary/convert_codemeta, but it's worth considering options.

**Comment by mhucka** [comment]
Agreed. I like that round logo, and that it looks similar to the previous one. I find using round logos is easier and produces nicer layours when more logos are added. We don't have examples of the latter situation in Caltech Library repos, but I've run into that for other projects – see the bottom of https://github.com/gillesPy2/GillesPy2 – and I bet we'll have a similar situation for Caltech Library at some point. 

I'll update this template accordingly.

**Comment by mhucka** [comment]
This is fixed with commit edf5d37.
