### ISSUE TITLE
Code of conduct green checkmark exists

### ISSUE THREAD

**Issue by t4k** [caltechlibrary/template#5]
The note in the wiki page is now obsolete: https://github.com/caltechlibrary/template/wiki/Lack-of-green-checkmark-for-code-of-conduct

**Comment by mhucka** [comment]
Oh, nice! Thanks for spotting that. I'll remove the wiki page.

**Comment by mhucka** [comment]
Done.

**Comment by mhucka** [comment]
P.S. This made me realize the wiki instructions were out of date with respect to other things, so I updated it now. 

Improvements welcome! Feel free to edit as needed.

https://github.com/caltechlibrary/template/wiki
